In [2]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sp
import timeit

In [3]:
def merge_sort(arr):
    if len(arr) > 1:
        mid = len(arr)//2
        L = arr[:mid]
        R = arr[mid:]

        merge_sort(L)
        merge_sort(R)
 
        i = j = k = 0

        while i < len(L) and j < len(R):
            if L[i] < R[j]:
                arr[k] = L[i]
                i += 1
            else:
                arr[k] = R[j]
                j += 1
            k += 1
        while i < len(L):
            arr[k] = L[i]
            i += 1
            k += 1
 
        while j < len(R):
            arr[k] = R[j]
            j += 1
            k += 1

In [4]:
def heapify(arr, n, i):
    largest = i  
    l = 2 * i + 1  
    r = 2 * i + 2     
 
    if l < n and arr[largest] < arr[l]:
        largest = l

    if r < n and arr[largest] < arr[r]:
        largest = r

    if largest != i:
        arr[i], arr[largest] = arr[largest], arr[i]  
        heapify(arr, n, largest)
 
 
def heap_sort(arr):
    n = len(arr)

    for i in range(n//2 - 1, -1, -1):
        heapify(arr, n, i)
 
    for i in range(n-1, 0, -1):
        arr[i], arr[0] = arr[0], arr[i]
        heapify(arr, i, 0)

In [5]:
def shell_sort(arr):
    interval = len(arr) // 2
    while interval > 0:
        for i in range(interval, len(arr)):
            temp = arr[i]
            j = i
            while j >= interval and arr[j - interval] > temp:
                arr[j] = arr[j - interval]
                j -= interval
            arr[j] = temp
        interval //= 2

In [6]:
def bubble_sort(arr):
    for i in range(len(arr)):
        for j in range(len(arr) - 1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]

In [7]:
def insertion_sort(arr):
    indexing_length = range(1, len(arr))
    for i in indexing_length:
        value_to_sort = arr[i]

        while ((arr[i-1] > value_to_sort) and (i > 0)):
            arr[i], arr[i-1] = arr[i-1], arr[i]
            i = i -1

In [8]:
def selection_sort(arr):
    indexing_length = range(0, len(arr)-1)

    for i in indexing_length:
        min_value = i

        for j in range(i+1, len(arr)):
            if arr[j] < arr[min_value]:
                min_value = j


        if min_value != i:
            arr[min_value], arr[i] = arr[i], arr[min_value]

In [9]:
def quick_sort(arr, left, right):
    i = left
    j = right
    pivot = arr[((i+j)//2)]
    while (i <= j):
        while (arr[i] < pivot): 
            i += 1
        while (arr[j] > pivot):
            j -= 1
        if (i <= j):
            temp = arr[i]
            arr[i] = arr[j]
            arr[j] = temp 
            i += 1
            j -= 1
    if (left < j): quick_sort(arr, left, j)
    if (i < right): quick_sort(arr, i, right)


Shell sort algorithm:  Shell sort is an algorithm that first sorts the elements far apart from each other and successively reduces the interval between the elements to be sorted. It is a generalized version of insertion sort.

In shell sort, elements at a specific interval are sorted. The interval between the elements is gradually decreased based on the sequence used. The performance of the shell sort depends on the type of sequence used for a given input array.

Time complexity: Best case: O(nlog(n)), Average: O(n(log(n))^2), Worse case: O(n(log(n))^2)

Space complexity: Worst case: O(1)

In [10]:
arr = np.random.randint(10000, size=(10000))
arr_shell_sort = arr
arr_shell_sort

array([ 156, 9588, 8177, ..., 1418, 2234, 4158])

In [11]:
arr_selections_sort = arr

start = timeit.default_timer()
shell_sort(arr_shell_sort)
stop = timeit.default_timer()

print('Time: ', stop - start)  

Time:  0.15453400000023976


In [12]:
arr_shell_sort

array([   0,    3,    6, ..., 9996, 9999, 9999])

Selection sort: Selection sort is an algorithm that selects the smallest element from an unsorted list in each iteration and places that element at the beginning of the unsorted list.

Time complexity: O(n^2)

Space complexity: O(1)

In [13]:
arr = np.random.randint(10000, size=(10000))
arr_selections_sort = arr
arr_selections_sort

array([4243, 3992, 3498, ..., 7653, 5208, 5694])

In [14]:
arr_selections_sort = arr

start = timeit.default_timer()
selection_sort(arr_selections_sort)
stop = timeit.default_timer()

print('Time: ', stop - start)  

Time:  17.185270299999956


In [15]:
arr_selections_sort

array([   1,    1,    2, ..., 9999, 9999, 9999])

Bubble sort: This is the most basic sorting function that every programmer knows (and no one uses it :v)

Time complexity: Best case: O(n)  -  Worst and Average case: O(n^2)

Space complexity: O(1)

In [16]:
arr = np.random.randint(10000, size=(10000))
arr_bubble_sort = arr
arr_bubble_sort

array([4152, 6025, 4246, ..., 1799, 2765, 6250])

In [17]:
start = timeit.default_timer()
bubble_sort(arr_bubble_sort)
stop = timeit.default_timer()

print('Time: ', stop - start)  

Time:  50.843752400000085


In [18]:
arr_bubble_sort

array([   0,    0,    1, ..., 9996, 9996, 9999])

Merge sort: Merge sort is a divide-and-conquer algorithm based on the idea of breaking down a list into several sub-lists until each sublist consists of a single element and merging those sublists in a manner that results into a sorted list.

Time complexity: O(nlog(n))

Space complexity: O(n)

In [22]:
arr = np.random.randint(100000000, size=(10000000)) #10^7
arr_merge_sort = arr.tolist()
arr.max() # I cannot do the merge sort on the numpy array, so I convert it to a list  - Because this is an optional algorithm so I wanna try a big number


99999997

In [23]:
start = timeit.default_timer()
merge_sort(arr_merge_sort)
stop = timeit.default_timer()

print('Time: ', stop - start)  

Time:  76.24381129999983


In [25]:
arr_merge_sort[10000000 - 1 ] #the last values (max) in increasing list - you can check the increasing list by running " arr_merge_sort " in next shell (trust me, it's too longggggggg, don't do this)

99999997

In [ ]:
arr_merge_sort

Insertion sort: Insertion sort is a sorting algorithm that places an unsorted element at its suitable place in each iteration.

Time complexity: Best case: O(n) - Worst, Average cases: O(n^2)

Space complexity: O(1)

In [26]:
arr = np.random.randint(10000, size=(10000))
arr_insertion_sort = arr
arr_insertion_sort

array([2811,  582, 8095, ..., 9169, 3856, 4800])

In [27]:
start = timeit.default_timer()  
insertion_sort(arr_insertion_sort)
stop = timeit.default_timer()

print('Time: ', stop - start)  

Time:  19.59337800000003


In [28]:
arr_insertion_sort

array([   0,    0,    1, ..., 9999, 9999, 9999])

Quick sort: Quicksort is an algorithm based on divide and conquer approach in which the array is split into subarrays and these sub-arrays are recursively called to sort the elements. // this is my favorite sort algorithm in programming, I learned it at grade 9.

Time complexity: Best case: O(nlog(n)) - Average: O(nlog(n)) - Worst case: O(n^2)

Space complexity: O(log(n))

In [32]:
arr = np.random.randint(100000000, size=(10000000))
arr_quick_sort = arr
arr_quick_sort

array([21438210, 42310323,  2237622, ..., 19344200, 33615104, 46350261])

In [33]:
start = timeit.default_timer()
quick_sort(arr_quick_sort, 0 , len(arr) -1)
stop = timeit.default_timer()

print('Time: ', stop - start)  

Time:  104.84076149999964


In [34]:
arr_quick_sort # Hmmmm.... it is slower than Merge Sort, despite the same time complexity..., maybe it's the worst case 

array([       6,       30,       42, ..., 99999986, 99999986, 99999993])

Heap sort: Heap sort works by visualizing the elements of the array as a special kind of complete binary tree called a heap. There're 2 types of heap (max heap and min heap)

Time complexity: O(nlog(n)) 

Space complexity: O(1)  - this is the best sort algorithm I've ever seen :))

In [35]:
arr = np.random.randint(10000, size=(10000))
arr_heap_sort = arr
arr_heap_sort

array([9030, 6052, 8478, ..., 4851, 3649, 6021])

In [36]:
start = timeit.default_timer()
heap_sort(arr_heap_sort)
stop = timeit.default_timer()

print('Time: ', stop - start)

Time:  0.18467020000025514


In [37]:
arr_heap_sort

array([   2,    2,    4, ..., 9994, 9997, 9998])

This this a sort function provided by python language to help programmers to do the sort quickly (or maybe they're lazy :3 )

This is Timsort (implemented by Tim Peter) derived from merge sort and insertion sort, but asymptotically it’s no better than merge sort. The time complexity: Best case: O(n) -- Avarage and Worse cases: O(nlog(n))

"Timsort can require a temp array containing as many as N//2 pointers, which means as many as 2*N extra bytes on 32-bit boxes. It can be expected to require a temp array this large when sorting random data; on data with significant structure, it may get away without using any extra heap memory." The worst case space complexity is O(N) and best case O(1)


In [42]:
arr = np.random.randint(1000000000, size=(1000000000)) #10^9
arr_auto_sort = arr
arr_auto_sort

array([745022405, 552374341, 585357211, ..., 739206249,  33259053,
       238944817])

In [43]:
start = timeit.default_timer()
arr_auto_sort.sort()
stop = timeit.default_timer()

print('Time: ', stop - start)  #surpriseeeee :v I didn't think that arr.sort() is significantly faster than my quicksort or mergesort as my project shown :v but it can't run on the tree structures :( so sad

Time:  123.52269560000013


In [44]:
arr_auto_sort

array([        0,         1,         1, ..., 999999993, 999999994,
       999999995])

Reference: https://www.bigocheatsheet.com/?goback=.gde_98713_member_241501229
https://en.wikipedia.org/wiki/Timsort
